#!/bin/bash
# ============================================================
# GPU Auto-Detection Script (runs on HOST before container starts)
# Generates docker-compose.override.yml with GPU config if available
# ============================================================

OVERRIDE_FILE="$(dirname "$0")/docker-compose.override.yml"

echo "[GPU Detect] Checking for NVIDIA GPU on host..."

# Check if nvidia-smi exists and reports a GPU
if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null 2>&1; then
    GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1)
    echo "[GPU Detect] Found NVIDIA GPU: ${GPU_NAME:-unknown}"
    echo "[GPU Detect] Enabling GPU passthrough for container"

    cat > "$OVERRIDE_FILE" << 'EOF'
# Auto-generated by detect-gpu.sh — DO NOT EDIT
# NVIDIA GPU detected on host, enabling passthrough
services:
  ros2:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
EOF

else
    echo "[GPU Detect] No NVIDIA GPU found — using software rendering"
    echo "[GPU Detect] (This is normal on Mac or systems without NVIDIA GPUs)"

    cat > "$OVERRIDE_FILE" << 'EOF'
# Auto-generated by detect-gpu.sh — DO NOT EDIT
# No NVIDIA GPU detected, container will use software rendering
services:
  ros2: {}
EOF

fi

echo "[GPU Detect] Wrote $OVERRIDE_FILE"
