services:
  ros2:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace/turtlebot3_ws:cached
      - turtlebot3-build:/workspace/turtlebot3_ws/build
      - turtlebot3-install:/workspace/turtlebot3_ws/install
      - turtlebot3-log:/workspace/turtlebot3_ws/log
    environment:
      - DISPLAY=:1
      - ROS_DISTRO=humble
      - ROS_DOMAIN_ID=30
      - TURTLEBOT3_MODEL=burger
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - QT_QPA_PLATFORM=xcb
    # Keep container running
    command: sleep infinity

volumes:
  turtlebot3-build:
  turtlebot3-install:
  turtlebot3-log:
